import { describe, expect, it } from 'vitest';
import { EventEmitter } from 'node:events';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { AgentAdapter, AgentEvent } from '../../../src/agent/types.js';
import { ActiveRuns } from '../../../src/bot/active-runs.js';
import { ProcessPool } from '../../../src/bot/process-pool.js';
import type { RunPolicyAllow } from '../../../src/policy/run-policy.js';
import { CodexRunExecutor } from '../../../src/runtime/codex-run-executor.js';
import { CodexRuntimeCoordinator } from '../../../src/runtime/codex-runtime-coordinator.js';
import { SessionCatalog } from '../../../src/session/catalog.js';

describe('CodexRunExecutor admission and steer streams', () => {
  it('applies policy admission and binds a steer subscriber to future events on the real run', async () => {
    const queue = new Queue(); const active = new ActiveRuns(); const pool = new ProcessPool(() => 1);
    const inputs: Array<{ messageId?: string }> = []; let submits = 0; const runtime = { submitMessage: async (input: { messageId?: string }) => { inputs.push(input); if (submits++ === 0) return { accepted: true, action: 'started', events: queue }; queue.push({ type: 'text', delta: 'during-rpc' }); await new Promise((resolve) => setImmediate(resolve)); return { accepted: true, action: 'steered', events: queue }; }, stop: async () => true, state: () => ({ state: 'idle' }) } as unknown as CodexRuntimeCoordinator;
    const executor = new CodexRunExecutor({ agent: agent(), pool, activeRuns: active }, runtime, active);
    await expect(executor.submit({ scopeId: 'expired', policy: policy({ expiresAt: 0 }) })).rejects.toMatchObject({ code: 'policy-expired' });
    const first = await executor.submit({ scopeId: 'scope', policy: policy() }); const firstSeen: AgentEvent[] = []; const firstPump = (async () => { for await (const event of first.subscribe()) firstSeen.push(event); })(); queue.push({ type: 'text', delta: 'old' }); await new Promise((resolve) => setImmediate(resolve));
    const steered = await executor.submit({ scopeId: 'scope', policy: policy({ prompt: 'steer' }), messageId: 'msg-2' }); const seen: AgentEvent[] = []; const collecting = (async () => { for await (const event of steered.subscribe()) seen.push(event); })();
    queue.push({ type: 'text', delta: 'new' }); queue.push({ type: 'done', terminationReason: 'normal' }); queue.close(); await collecting;
    await firstPump; expect(steered.run).toBe(first.run); expect(inputs.every((value) => typeof value.messageId === 'string' && value.messageId.length > 0)).toBe(true); expect(firstSeen).toEqual([{ type: 'text', delta: 'old' }]); expect(seen).toEqual([{ type: 'text', delta: 'during-rpc' }, { type: 'text', delta: 'new' }, { type: 'done', terminationReason: 'normal' }]); expect(seen.filter((event) => event.type === 'done')).toHaveLength(1);
  });
  it('rolls back stream ownership when steer RPC fails', async () => {
    const queue = new Queue(); const active = new ActiveRuns(); let submits = 0; const runtime = { submitMessage: async () => { if (submits++ === 0) return { accepted: true, action: 'started', events: queue }; queue.push({ type: 'text', delta: 'during-failed-rpc' }); throw new Error('not steerable'); }, stop: async () => true, state: () => ({ state: 'idle' }) } as unknown as CodexRuntimeCoordinator;
    const executor = new CodexRunExecutor({ agent: agent(), pool: new ProcessPool(() => 1), activeRuns: active }, runtime, active); const first = await executor.submit({ scopeId: 'scope', policy: policy(), observability: { profile: 'p', agent: 'codex', source: 'web', stage: 'test' } }); const seen: AgentEvent[] = []; const pump = (async () => { for await (const event of first.subscribe()) seen.push(event); })();
    await expect(executor.submit({ scopeId: 'scope', policy: policy(), observability: { profile: 'p', agent: 'codex', source: 'web', stage: 'test' } })).rejects.toThrow('not steerable'); queue.push({ type: 'text', delta: 'after-failure' }); queue.push({ type: 'done', terminationReason: 'normal' }); queue.close(); await pump;
    expect(seen).toEqual([{ type: 'text', delta: 'during-failed-rpc' }, { type: 'text', delta: 'after-failure' }, { type: 'done', terminationReason: 'normal' }]);
  });
  it('generates an id that reconciles an ambiguous start without resubmitting the turn', async () => {
    const rpc = new AmbiguousRpc(); const dir = await mkdtemp(join(tmpdir(), 'codex-executor-')); const coordinator = new CodexRuntimeCoordinator(rpc, new SessionCatalog(join(dir, 'catalog.json')), 20, { reconcileAttempts: 1, reconcileBackoffMs: 1 }); const active = new ActiveRuns(); const executor = new CodexRunExecutor({ agent: agent(), pool: new ProcessPool(() => 1), activeRuns: active }, coordinator, active);
    const execution = await executor.submit({ scopeId: 'scope', policy: policy() }); expect(execution.runId).toBeTruthy(); expect(rpc.calls.filter((method) => method === 'turn/start')).toHaveLength(1); expect(rpc.clientId).toMatch(/\S/); expect(coordinator.state('scope')).toMatchObject({ state: 'running', turnId: 'turn-1' });
    rpc.emit('notification', { method: 'turn/completed', params: { threadId: 'thread-1', turn: { id: 'turn-1', status: 'completed' } } }); for await (const _ of execution.subscribe()) { /* drain */ }
  });
  it('does not start a different-identity turn before the old physical run releases admission', async () => {
    const rpc = new GateRpc(); const dir = await mkdtemp(join(tmpdir(), 'codex-gate-')); const coordinator = new CodexRuntimeCoordinator(rpc, new SessionCatalog(join(dir, 'catalog.json'))); const active = new ActiveRuns(); const executor = new CodexRunExecutor({ agent: agent(), pool: new ProcessPool(() => 1), activeRuns: active }, coordinator, active);
    const first = await executor.submit({ scopeId: 'scope', policy: policy() }); const second = executor.submit({ scopeId: 'scope', policy: policy({ cwdRealpath: '/other', requestedCwd: '/other', policyFingerprint: 'other' }), images: ['/tmp/image.png'] }); await new Promise((resolve) => setImmediate(resolve)); expect(rpc.calls.filter((method) => method === 'turn/start')).toHaveLength(1);
    rpc.emit('notification', { method: 'turn/completed', params: { threadId: 'thread-1', turn: { id: 'turn-1', status: 'completed' } } }); for await (const _ of first.subscribe()) { /* drain */ } const next = await second; expect(rpc.calls.filter((method) => method === 'turn/start')).toHaveLength(2); expect(next.runId).toBeTruthy();
    rpc.emit('notification', { method: 'turn/completed', params: { threadId: 'thread-1', turn: { id: 'turn-2', status: 'completed' } } }); for await (const _ of next.subscribe()) { /* drain */ }
  });
  it('serializes concurrent steer claims for one scope', async () => {
    const queue = new Queue(); let calls = 0; const runtime = { submitMessage: async () => { if (calls++ === 0) return { accepted: true, action: 'started', events: queue }; await new Promise((resolve) => setImmediate(resolve)); return { accepted: true, action: 'steered', events: queue }; }, stop: async () => true, state: () => ({ state: 'idle' }) } as unknown as CodexRuntimeCoordinator; const active = new ActiveRuns(); const executor = new CodexRunExecutor({ agent: agent(), pool: new ProcessPool(() => 1), activeRuns: active }, runtime, active);
    const first = await executor.submit({ scopeId: 'scope', policy: policy(), observability: { profile: 'p', agent: 'codex', source: 'web', stage: 'test' } }); const [one, two] = await Promise.all([executor.submit({ scopeId: 'scope', policy: policy({ prompt: 'one' }), observability: { profile: 'p', agent: 'codex', source: 'web', stage: 'test' } }), executor.submit({ scopeId: 'scope', policy: policy({ prompt: 'two' }), observability: { profile: 'p', agent: 'codex', source: 'web', stage: 'test' } })]); expect(one.run).toBe(first.run); expect(two.run).toBe(first.run); expect(calls).toBe(3); queue.push({ type: 'done', terminationReason: 'normal' }); queue.close();
  });
  it('rechecks policy expiry after handoff and pool wait before starting the next turn', async () => {
    let now = 0; const rpc = new GateRpc(); const dir = await mkdtemp(join(tmpdir(), 'codex-expiry-')); const coordinator = new CodexRuntimeCoordinator(rpc, new SessionCatalog(join(dir, 'catalog.json'))); const active = new ActiveRuns(); const executor = new CodexRunExecutor({ agent: agent(), pool: new ProcessPool(() => 1), activeRuns: active, now: () => now }, coordinator, active);
    const first = await executor.submit({ scopeId: 'scope', policy: policy({ expiresAt: 100 }) }); const second = executor.submit({ scopeId: 'scope', policy: policy({ requestedCwd: '/other', cwdRealpath: '/other', policyFingerprint: 'other', expiresAt: 100 }) }); await new Promise((resolve) => setImmediate(resolve)); expect(rpc.calls.filter((method) => method === 'turn/start')).toHaveLength(1);
    rpc.emit('notification', { method: 'turn/completed', params: { threadId: 'thread-1', turn: { id: 'turn-1', status: 'completed' } } }); now = 200; for await (const _ of first.subscribe()) { /* drain */ } await expect(second).rejects.toMatchObject({ code: 'policy-expired' }); expect(rpc.calls.filter((method) => method === 'turn/start')).toHaveLength(1);
  });
  it('treats a model change as identity handoff instead of steering the old turn', async () => {
    const rpc = new GateRpc(); const dir = await mkdtemp(join(tmpdir(), 'codex-model-')); const coordinator = new CodexRuntimeCoordinator(rpc, new SessionCatalog(join(dir, 'catalog.json'))); const active = new ActiveRuns(); const executor = new CodexRunExecutor({ agent: agent(), pool: new ProcessPool(() => 1), activeRuns: active }, coordinator, active); const first = await executor.submit({ scopeId: 'scope', policy: policy(), model: 'model-a' }); const second = executor.submit({ scopeId: 'scope', policy: policy(), model: 'model-b' }); await new Promise((resolve) => setImmediate(resolve)); expect(rpc.calls.filter((method) => method === 'turn/steer')).toHaveLength(0); rpc.emit('notification', { method: 'turn/completed', params: { threadId: 'thread-1', turn: { id: 'turn-1', status: 'completed' } } }); for await (const _ of first.subscribe()) { /* drain */ } const next = await second; expect(rpc.calls.filter((method) => method === 'turn/start')).toHaveLength(2); rpc.emit('notification', { method: 'turn/completed', params: { threadId: 'thread-1', turn: { id: 'turn-2', status: 'completed' } } }); for await (const _ of next.subscribe()) { /* drain */ }
  });
  it('rejects coordinator-owned running turns when local ActiveRuns has no owner', async () => {
    let submissions = 0; const runtime = { state: () => ({ state: 'running' }), submitMessage: async () => { submissions++; return { accepted: true, action: 'steered' }; }, stop: async () => true } as unknown as CodexRuntimeCoordinator; const active = new ActiveRuns(); const executor = new CodexRunExecutor({ agent: agent(), pool: new ProcessPool(() => 1), activeRuns: active }, runtime, active); await expect(executor.submit({ scopeId: 'scope', policy: policy() })).rejects.toMatchObject({ code: 'run-already-active' }); expect(submissions).toBe(0); expect(active.get('scope')).toBeUndefined();
  });
});
class AmbiguousRpc extends EventEmitter { calls: string[] = []; clientId = ''; async request<T>(method: string, params?: unknown): Promise<T> { this.calls.push(method); if (method === 'thread/start') return { thread: { id: 'thread-1' } } as T; if (method === 'turn/start') { this.clientId = String((params as { clientUserMessageId?: string }).clientUserMessageId); this.emit('disconnect'); this.emit('ready'); throw new Error('lost response'); } if (method === 'thread/read') return { thread: { id: 'thread-1', turns: [{ id: 'turn-1', status: 'inProgress', items: [{ type: 'userMessage', clientId: this.clientId }] }] } } as T; return {} as T; } }
class GateRpc extends EventEmitter { calls: string[] = []; turn = 0; async request<T>(method: string): Promise<T> { this.calls.push(method); if (method === 'thread/start' || method === 'thread/resume') return { thread: { id: 'thread-1' } } as T; if (method === 'turn/start') return { turn: { id: `turn-${++this.turn}` } } as T; return {} as T; } }
class Queue implements AsyncIterable<AgentEvent> { private values: AgentEvent[] = []; private wake?: () => void; private done = false; push(value: AgentEvent) { this.values.push(value); this.wake?.(); } close() { this.done = true; this.wake?.(); } async *[Symbol.asyncIterator]() { while (!this.done || this.values.length) { if (this.values.length) yield this.values.shift()!; else await new Promise<void>((resolve) => { this.wake = resolve; }); } } }
function agent(): AgentAdapter { return { id: 'codex', displayName: 'Codex', isAvailable: async () => true, run: () => { throw new Error('legacy run must not be used'); } }; }
function policy(overrides: Partial<RunPolicyAllow> = {}): RunPolicyAllow { return { ok: true, prompt: 'hello', requestedCwd: '/work', cwdRealpath: '/work', accessMode: 'workspace', sandbox: 'workspace-write', permissionMode: 'acceptEdits', access: { ok: true, reason: 'allowed-user' }, attachments: [], policyFingerprint: 'fp', expiresAt: Date.now() + 60_000, ...overrides }; }
